import XLSX from 'xlsx';

const data = [
  {
    "First Name": "Jane",
    "Last Name": "Doe",
    "Email Address": "jane.doe@example.com",
    "Phone Number": "+1 (555) 019-2834",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/janedoe",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Computer Science",
    "Institution / University": "Stanford University",
    "Graduation Year": 2022,
    "Cumulative GPA": 3.85,
    "Previous / Current Job Title": "Software Engineer I",
    "Company Name": "Acme Corp",
    "Years of Professional Experience": 2,
    "Primary Domain Skillset": "Frontend",
    "Currently Employed": "true",
    "Target Hiring Level": "Mid Developer",
    "Desired Annual Salary ($ USD)": 115000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Jane Doe"
  },
  {
    "First Name": "John",
    "Last Name": "Smith",
    "Email Address": "john.smith@techdomain.org",
    "Phone Number": "+1 (555) 042-9988",
    "LinkedIn or Portfolio URL": "https://github.com/johnsmithtech",
    "Highest Degree Level": "Master's Degree",
    "Field of Study": "Software Engineering",
    "Institution / University": "Carnegie Mellon",
    "Graduation Year": 2020,
    "Cumulative GPA": 3.92,
    "Previous / Current Job Title": "Senior Software Engineer",
    "Company Name": "Globex Systems",
    "Years of Professional Experience": 6,
    "Primary Domain Skillset": "Backend",
    "Currently Employed": "false",
    "Target Hiring Level": "Senior Developer",
    "Desired Annual Salary ($ USD)": 155000,
    "Availability / Notice Period": "Immediate",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "John Smith"
  },
  {
    "First Name": "Anya",
    "Last Name": "Kovalenko",
    "Email Address": "anya.k@devmail.net",
    "Phone Number": "+44 20 7946 0192",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/anyakoval",
    "Highest Degree Level": "Self-Taught / Bootcamp",
    "Field of Study": "Web Development",
    "Institution / University": "General Assembly",
    "Graduation Year": 2021,
    "Cumulative GPA": 4.0,
    "Previous / Current Job Title": "Junior Web Developer",
    "Company Name": "StartUp Labs",
    "Years of Professional Experience": 3,
    "Primary Domain Skillset": "Fullstack",
    "Currently Employed": "true",
    "Target Hiring Level": "Mid Developer",
    "Desired Annual Salary ($ USD)": 98000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Hybrid",
    "Certification Consent": "true",
    "Digital Signature": "Anya Kovalenko"
  },
  {
    "First Name": "Carlos",
    "Last Name": "Mendez",
    "Email Address": "carlos.mendez@cloudbuilders.com",
    "Phone Number": "+1 (555) 789-0123",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/carlos-mendez-cloud",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Information Technology",
    "Institution / University": "UT Austin",
    "Graduation Year": 2018,
    "Cumulative GPA": 3.65,
    "Previous / Current Job Title": "Infrastructure Engineer",
    "Company Name": "Cloud Dynamics",
    "Years of Professional Experience": 8,
    "Primary Domain Skillset": "DevOps",
    "Currently Employed": "true",
    "Target Hiring Level": "Lead Engineer",
    "Desired Annual Salary ($ USD)": 170000,
    "Availability / Notice Period": "2 Months",
    "Work Style Preference": "Hybrid",
    "Certification Consent": "true",
    "Digital Signature": "Carlos Mendez"
  },
  {
    "First Name": "Yuki",
    "Last Name": "Tanaka",
    "Email Address": "yuki.tanaka@tokyotech.jp",
    "Phone Number": "+81 3 5555 0143",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/yukitanaka-ds",
    "Highest Degree Level": "Ph.D.",
    "Field of Study": "Computer Science / AI",
    "Institution / University": "Tokyo University",
    "Graduation Year": 2019,
    "Cumulative GPA": 3.98,
    "Previous / Current Job Title": "Research Scientist",
    "Company Name": "AIST Japan",
    "Years of Professional Experience": 5,
    "Primary Domain Skillset": "Data Science",
    "Currently Employed": "true",
    "Target Hiring Level": "Lead Engineer",
    "Desired Annual Salary ($ USD)": 185000,
    "Availability / Notice Period": "3+ Months",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Yuki Tanaka"
  },
  {
    "First Name": "Liam",
    "Last Name": "Wilson",
    "Email Address": "liam.wilson@devnet.com",
    "Phone Number": "+1 (555) 014-7733",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/liamwilson",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Computer Science",
    "Institution / University": "UC Berkeley",
    "Graduation Year": 2021,
    "Cumulative GPA": 3.78,
    "Previous / Current Job Title": "Software Engineer",
    "Company Name": "PixelTech",
    "Years of Professional Experience": 3,
    "Primary Domain Skillset": "Fullstack",
    "Currently Employed": "true",
    "Target Hiring Level": "Mid Developer",
    "Desired Annual Salary ($ USD)": 105000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Liam Wilson"
  },
  {
    "First Name": "Emma",
    "Last Name": "Watson",
    "Email Address": "emma.watson@codelabs.io",
    "Phone Number": "+44 20 7946 0543",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/emmawatson-code",
    "Highest Degree Level": "Master's Degree",
    "Field of Study": "Human-Computer Interaction",
    "Institution / University": "UCL London",
    "Graduation Year": 2017,
    "Cumulative GPA": 3.90,
    "Previous / Current Job Title": "UI Engineer",
    "Company Name": "DesignSystems Ltd",
    "Years of Professional Experience": 7,
    "Primary Domain Skillset": "Frontend",
    "Currently Employed": "false",
    "Target Hiring Level": "Senior Developer",
    "Desired Annual Salary ($ USD)": 135000,
    "Availability / Notice Period": "Immediate",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Emma Watson"
  },
  {
    "First Name": "Noah",
    "Last Name": "Chen",
    "Email Address": "noah.chen@datastack.org",
    "Phone Number": "+1 (555) 332-9988",
    "LinkedIn or Portfolio URL": "https://github.com/noahchen",
    "Highest Degree Level": "Ph.D.",
    "Field of Study": "Data Science",
    "Institution / University": "MIT",
    "Graduation Year": 2016,
    "Cumulative GPA": 3.95,
    "Previous / Current Job Title": "Principal Data Scientist",
    "Company Name": "Neural Corp",
    "Years of Professional Experience": 9,
    "Primary Domain Skillset": "Data Science",
    "Currently Employed": "true",
    "Target Hiring Level": "Lead Engineer",
    "Desired Annual Salary ($ USD)": 195000,
    "Availability / Notice Period": "2 Months",
    "Work Style Preference": "Hybrid",
    "Certification Consent": "true",
    "Digital Signature": "Noah Chen"
  },
  {
    "First Name": "Olivia",
    "Last Name": "Martinez",
    "Email Address": "olivia.martinez@testingpros.com",
    "Phone Number": "+1 (555) 443-8822",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/oliviamartinez-qa",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Information Systems",
    "Institution / University": "Arizona State",
    "Graduation Year": 2019,
    "Cumulative GPA": 3.55,
    "Previous / Current Job Title": "QA Engineer",
    "Company Name": "BugFree Software",
    "Years of Professional Experience": 5,
    "Primary Domain Skillset": "QA / Testing",
    "Currently Employed": "true",
    "Target Hiring Level": "Mid Developer",
    "Desired Annual Salary ($ USD)": 95000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Onsite",
    "Certification Consent": "true",
    "Digital Signature": "Olivia Martinez"
  },
  {
    "First Name": "William",
    "Last Name": "Taylor",
    "Email Address": "william.taylor@backendsystems.net",
    "Phone Number": "+1 (555) 887-2299",
    "LinkedIn or Portfolio URL": "https://github.com/wtaylor-backend",
    "Highest Degree Level": "Self-Taught / Bootcamp",
    "Field of Study": "Software Engineering",
    "Institution / University": "App Academy",
    "Graduation Year": 2018,
    "Cumulative GPA": 4.0,
    "Previous / Current Job Title": "Senior Systems Engineer",
    "Company Name": "DataGrid LLC",
    "Years of Professional Experience": 6,
    "Primary Domain Skillset": "Backend",
    "Currently Employed": "true",
    "Target Hiring Level": "Senior Developer",
    "Desired Annual Salary ($ USD)": 145000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "William Taylor"
  },
  {
    "First Name": "Sophia",
    "Last Name": "Brown",
    "Email Address": "sophia.b@mobiledevs.co",
    "Phone Number": "+1 (555) 776-3390",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/sophiabrown-ios",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Mobile Application Design",
    "Institution / University": "Georgia Tech",
    "Graduation Year": 2020,
    "Cumulative GPA": 3.72,
    "Previous / Current Job Title": "iOS Developer",
    "Company Name": "SwiftApps Corp",
    "Years of Professional Experience": 4,
    "Primary Domain Skillset": "Mobile",
    "Currently Employed": "false",
    "Target Hiring Level": "Mid Developer",
    "Desired Annual Salary ($ USD)": 110000,
    "Availability / Notice Period": "Immediate",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Sophia Brown"
  },
  {
    "First Name": "James",
    "Last Name": "Anderson",
    "Email Address": "james.anderson@cloudops.org",
    "Phone Number": "+1 (555) 909-3234",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/james-anderson-infra",
    "Highest Degree Level": "Master's Degree",
    "Field of Study": "Cloud Computing",
    "Institution / University": "University of Washington",
    "Graduation Year": 2015,
    "Cumulative GPA": 3.82,
    "Previous / Current Job Title": "Lead DevOps Architect",
    "Company Name": "Global Cloud Services",
    "Years of Professional Experience": 10,
    "Primary Domain Skillset": "DevOps",
    "Currently Employed": "true",
    "Target Hiring Level": "Lead Engineer",
    "Desired Annual Salary ($ USD)": 180000,
    "Availability / Notice Period": "3+ Months",
    "Work Style Preference": "Hybrid",
    "Certification Consent": "true",
    "Digital Signature": "James Anderson"
  },
  {
    "First Name": "Isabella",
    "Last Name": "Thomas",
    "Email Address": "isabella.thomas@reactstudios.io",
    "Phone Number": "+1 (555) 123-9876",
    "LinkedIn or Portfolio URL": "https://github.com/isabellathomas-web",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Computer Science",
    "Institution / University": "University of Michigan",
    "Graduation Year": 2022,
    "Cumulative GPA": 3.88,
    "Previous / Current Job Title": "Frontend Developer",
    "Company Name": "WebScale Solutions",
    "Years of Professional Experience": 2,
    "Primary Domain Skillset": "Frontend",
    "Currently Employed": "true",
    "Target Hiring Level": "Mid Developer",
    "Desired Annual Salary ($ USD)": 100000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Isabella Thomas"
  },
  {
    "First Name": "Benjamin",
    "Last Name": "Jackson",
    "Email Address": "ben.jackson@stackbuilders.com",
    "Phone Number": "+1 (555) 456-0987",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/benjamin-jackson-dev",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Software Engineering",
    "Institution / University": "Purdue University",
    "Graduation Year": 2017,
    "Cumulative GPA": 3.69,
    "Previous / Current Job Title": "Senior Software Architect",
    "Company Name": "Enterprise Systems",
    "Years of Professional Experience": 7,
    "Primary Domain Skillset": "Fullstack",
    "Currently Employed": "true",
    "Target Hiring Level": "Senior Developer",
    "Desired Annual Salary ($ USD)": 150000,
    "Availability / Notice Period": "2 Months",
    "Work Style Preference": "Hybrid",
    "Certification Consent": "true",
    "Digital Signature": "Benjamin Jackson"
  },
  {
    "First Name": "Mia",
    "Last Name": "White",
    "Email Address": "mia.white@datascienceinc.net",
    "Phone Number": "+1 (555) 789-3456",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/mia-white-analytics",
    "Highest Degree Level": "Master's Degree",
    "Field of Study": "Statistics & AI",
    "Institution / University": "Columbia University",
    "Graduation Year": 2019,
    "Cumulative GPA": 3.91,
    "Previous / Current Job Title": "Data Scientist",
    "Company Name": "Insight Analytics",
    "Years of Professional Experience": 5,
    "Primary Domain Skillset": "Data Science",
    "Currently Employed": "false",
    "Target Hiring Level": "Senior Developer",
    "Desired Annual Salary ($ USD)": 140000,
    "Availability / Notice Period": "Immediate",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Mia White"
  },
  {
    "First Name": "Lucas",
    "Last Name": "Harris",
    "Email Address": "lucas.harris@mobilecoders.tech",
    "Phone Number": "+1 (555) 890-5678",
    "LinkedIn or Portfolio URL": "https://github.com/lucasharris-android",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Computer Science",
    "Institution / University": "UT Dallas",
    "Graduation Year": 2021,
    "Cumulative GPA": 3.61,
    "Previous / Current Job Title": "Android Developer",
    "Company Name": "AppFactory LLC",
    "Years of Professional Experience": 3,
    "Primary Domain Skillset": "Mobile",
    "Currently Employed": "true",
    "Target Hiring Level": "Mid Developer",
    "Desired Annual Salary ($ USD)": 102000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Hybrid",
    "Certification Consent": "true",
    "Digital Signature": "Lucas Harris"
  },
  {
    "First Name": "Charlotte",
    "Last Name": "Martin",
    "Email Address": "charlotte.m@securitybuilders.org",
    "Phone Number": "+1 (555) 901-7890",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/charlottemartin-sec",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Cybersecurity",
    "Institution / University": "Penn State",
    "Graduation Year": 2018,
    "Cumulative GPA": 3.76,
    "Previous / Current Job Title": "DevSecOps Specialist",
    "Company Name": "SecureNet Solutions",
    "Years of Professional Experience": 6,
    "Primary Domain Skillset": "DevOps",
    "Currently Employed": "true",
    "Target Hiring Level": "Senior Developer",
    "Desired Annual Salary ($ USD)": 160000,
    "Availability / Notice Period": "2 Months",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Charlotte Martin"
  },
  {
    "First Name": "Henry",
    "Last Name": "Thompson",
    "Email Address": "henry.t@serverside.io",
    "Phone Number": "+1 (555) 012-3456",
    "LinkedIn or Portfolio URL": "https://github.com/henrythompson-srv",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Computer Engineering",
    "Institution / University": "Virginia Tech",
    "Graduation Year": 2023,
    "Cumulative GPA": 3.80,
    "Previous / Current Job Title": "Junior Backend Developer",
    "Company Name": "Microservices Inc",
    "Years of Professional Experience": 1,
    "Primary Domain Skillset": "Backend",
    "Currently Employed": "true",
    "Target Hiring Level": "Junior Developer",
    "Desired Annual Salary ($ USD)": 85000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Remote",
    "Certification Consent": "true",
    "Digital Signature": "Henry Thompson"
  },
  {
    "First Name": "Evelyn",
    "Last Name": "Garcia",
    "Email Address": "evelyn.garcia@fullstackers.dev",
    "Phone Number": "+1 (555) 234-5678",
    "LinkedIn or Portfolio URL": "https://linkedin.com/in/evelyngarcia-dev",
    "Highest Degree Level": "Bachelor's Degree",
    "Field of Study": "Computer Science",
    "Institution / University": "UC San Diego",
    "Graduation Year": 2017,
    "Cumulative GPA": 3.74,
    "Previous / Current Job Title": "Lead Fullstack Engineer",
    "Company Name": "DevSaaS Ltd",
    "Years of Professional Experience": 7,
    "Primary Domain Skillset": "Fullstack",
    "Currently Employed": "true",
    "Target Hiring Level": "Lead Engineer",
    "Desired Annual Salary ($ USD)": 175000,
    "Availability / Notice Period": "1 Month",
    "Work Style Preference": "Hybrid",
    "Certification Consent": "true",
    "Digital Signature": "Evelyn Garcia"
  }
];

const worksheet = XLSX.utils.json_to_sheet(data);
const workbook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, worksheet, "Job_Applications");
XLSX.writeFile(workbook, "d:\\SACHIN RAWAL FILES\\FormPilot\\job_sample_data.xlsx");
console.log("Excel file successfully created at d:\\SACHIN RAWAL FILES\\FormPilot\\job_sample_data.xlsx!");
